/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_AMF_Identifier_H_
#define	_AMF_Identifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AMF-Identifier */
typedef BIT_STRING_t	 AMF_Identifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AMF_Identifier;
asn_struct_free_f AMF_Identifier_free;
asn_struct_print_f AMF_Identifier_print;
asn_constr_check_f AMF_Identifier_constraint;
ber_type_decoder_f AMF_Identifier_decode_ber;
der_type_encoder_f AMF_Identifier_encode_der;
xer_type_decoder_f AMF_Identifier_decode_xer;
xer_type_encoder_f AMF_Identifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AMF_Identifier_H_ */
#include <asn_internal.h>
