/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_NG_5G_S_TMSI_H_
#define	_NG_5G_S_TMSI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NG-5G-S-TMSI */
typedef BIT_STRING_t	 NG_5G_S_TMSI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NG_5G_S_TMSI;
asn_struct_free_f NG_5G_S_TMSI_free;
asn_struct_print_f NG_5G_S_TMSI_print;
asn_constr_check_f NG_5G_S_TMSI_constraint;
ber_type_decoder_f NG_5G_S_TMSI_decode_ber;
der_type_encoder_f NG_5G_S_TMSI_encode_der;
xer_type_decoder_f NG_5G_S_TMSI_decode_xer;
xer_type_encoder_f NG_5G_S_TMSI_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NG_5G_S_TMSI_H_ */
#include <asn_internal.h>
