/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetupRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetupRequest_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_InitialUE_Identity;
extern struct asn_TYPE_descriptor_s asn_DEF_EstablishmentCause;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetup;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetup_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetup_v1700_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RadioBearerConfig;
extern struct asn_TYPE_descriptor_s asn_DEF_SL_ConfigDedicatedNR_r16;
extern struct asn_TYPE_descriptor_s asn_DEF_SL_L2RemoteUE_Config_r17;
extern struct asn_TYPE_descriptor_s asn_DEF_RRC_TransactionIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetupComplete;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetupComplete_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetupComplete_v1610_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetupComplete_v1690_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetupComplete_v1700_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCSetupComplete_v1800_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RegisteredAMF;
extern struct asn_TYPE_descriptor_s asn_DEF_S_NSSAI;
extern struct asn_TYPE_descriptor_s asn_DEF_NG_5G_S_TMSI;
extern struct asn_TYPE_descriptor_s asn_DEF_DedicatedNAS_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_AMF_Identifier;
extern struct asn_TYPE_descriptor_s asn_DEF_PLMN_Identity;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_MeasurementsAvailable_r16;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCReject;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCReject_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RejectWaitTime;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module NR-RRC-Definitions in RRC.asn */
	&asn_DEF_RRCSetupRequest,	
	&asn_DEF_RRCSetupRequest_IEs,	
	&asn_DEF_InitialUE_Identity,	
	&asn_DEF_EstablishmentCause,	
	&asn_DEF_RRCSetup,	
	&asn_DEF_RRCSetup_IEs,	
	&asn_DEF_RRCSetup_v1700_IEs,	
	&asn_DEF_RadioBearerConfig,	
	&asn_DEF_SL_ConfigDedicatedNR_r16,	
	&asn_DEF_SL_L2RemoteUE_Config_r17,	
	&asn_DEF_RRC_TransactionIdentifier,	
	&asn_DEF_RRCSetupComplete,	
	&asn_DEF_RRCSetupComplete_IEs,	
	&asn_DEF_RRCSetupComplete_v1610_IEs,	
	&asn_DEF_RRCSetupComplete_v1690_IEs,	
	&asn_DEF_RRCSetupComplete_v1700_IEs,	
	&asn_DEF_RRCSetupComplete_v1800_IEs,	
	&asn_DEF_RegisteredAMF,	
	&asn_DEF_S_NSSAI,	
	&asn_DEF_NG_5G_S_TMSI,	
	&asn_DEF_DedicatedNAS_Message,	
	&asn_DEF_AMF_Identifier,	
	&asn_DEF_PLMN_Identity,	
	&asn_DEF_UE_MeasurementsAvailable_r16,	
	&asn_DEF_RRCReject,	
	&asn_DEF_RRCReject_IEs,	
	&asn_DEF_RejectWaitTime,	
	0
};

