/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RadioBearerConfig_H_
#define	_RadioBearerConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RadioBearerConfig */
typedef struct RadioBearerConfig {
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioBearerConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioBearerConfig;

#ifdef __cplusplus
}
#endif

#endif	/* _RadioBearerConfig_H_ */
#include <asn_internal.h>
