/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RegisteredAMF_H_
#define	_RegisteredAMF_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AMF-Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PLMN_Identity;

/* RegisteredAMF */
typedef struct RegisteredAMF {
	struct PLMN_Identity	*plmn_Identity	/* OPTIONAL */;
	AMF_Identifier_t	 amf_Identifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegisteredAMF_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegisteredAMF;

#ifdef __cplusplus
}
#endif

#endif	/* _RegisteredAMF_H_ */
#include <asn_internal.h>
