/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RejectWaitTime_H_
#define	_RejectWaitTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RejectWaitTime */
typedef long	 RejectWaitTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RejectWaitTime;
asn_struct_free_f RejectWaitTime_free;
asn_struct_print_f RejectWaitTime_print;
asn_constr_check_f RejectWaitTime_constraint;
ber_type_decoder_f RejectWaitTime_decode_ber;
der_type_encoder_f RejectWaitTime_encode_der;
xer_type_decoder_f RejectWaitTime_decode_xer;
xer_type_encoder_f RejectWaitTime_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RejectWaitTime_H_ */
#include <asn_internal.h>
