/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCReject_IEs_H_
#define	_RRCReject_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RejectWaitTime.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCReject-IEs */
typedef struct RRCReject_IEs {
	RejectWaitTime_t	*waitTime	/* OPTIONAL */;
	OCTET_STRING_t	*lateNonCriticalExtension	/* OPTIONAL */;
	struct RRCReject_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCReject_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCReject_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCReject_IEs_H_ */
#include <asn_internal.h>
