/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetup_v1700_IEs_H_
#define	_RRCSetup_v1700_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SL_ConfigDedicatedNR_r16;
struct SL_L2RemoteUE_Config_r17;

/* RRCSetup-v1700-IEs */
typedef struct RRCSetup_v1700_IEs {
	struct SL_ConfigDedicatedNR_r16	*sl_ConfigDedicatedNR_r17	/* OPTIONAL */;
	struct SL_L2RemoteUE_Config_r17	*sl_L2RemoteUE_Config_r17	/* OPTIONAL */;
	struct RRCSetup_v1700_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCSetup_v1700_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCSetup_v1700_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCSetup_v1700_IEs_H_ */
#include <asn_internal.h>
