/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_RRCSetupComplete_v1690_IEs_H_
#define	_RRCSetupComplete_v1690_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16 {
	RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16_true	= 0
} e_RRCSetupComplete_v1690_IEs__ul_RRC_Segmentation_r16;

/* Forward declarations */
struct RRCSetupComplete_v1700_IEs;

/* RRCSetupComplete-v1690-IEs */
typedef struct RRCSetupComplete_v1690_IEs {
	long	*ul_RRC_Segmentation_r16	/* OPTIONAL */;
	struct RRCSetupComplete_v1700_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCSetupComplete_v1690_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ul_RRC_Segmentation_r16_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCSetupComplete_v1690_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCSetupComplete_v1690_IEs_H_ */
#include <asn_internal.h>
