/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#include "RRCSetupComplete-v1610-IEs.h"

#include "UE-MeasurementsAvailable-r16.h"
#include "RRCSetupComplete-v1690-IEs.h"
static int
iab_NodeIndication_r16_2_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
iab_NodeIndication_r16_2_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
iab_NodeIndication_r16_2_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	iab_NodeIndication_r16_2_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
iab_NodeIndication_r16_2_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	iab_NodeIndication_r16_2_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
iab_NodeIndication_r16_2_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	iab_NodeIndication_r16_2_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
iab_NodeIndication_r16_2_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	iab_NodeIndication_r16_2_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
iab_NodeIndication_r16_2_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	iab_NodeIndication_r16_2_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
iab_NodeIndication_r16_2_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	iab_NodeIndication_r16_2_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
idleMeasAvailable_r16_4_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
idleMeasAvailable_r16_4_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
idleMeasAvailable_r16_4_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	idleMeasAvailable_r16_4_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
idleMeasAvailable_r16_4_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	idleMeasAvailable_r16_4_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
idleMeasAvailable_r16_4_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	idleMeasAvailable_r16_4_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
idleMeasAvailable_r16_4_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	idleMeasAvailable_r16_4_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
idleMeasAvailable_r16_4_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	idleMeasAvailable_r16_4_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
idleMeasAvailable_r16_4_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	idleMeasAvailable_r16_4_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
mobilityHistoryAvail_r16_7_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
mobilityHistoryAvail_r16_7_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
mobilityHistoryAvail_r16_7_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	mobilityHistoryAvail_r16_7_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
mobilityHistoryAvail_r16_7_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	mobilityHistoryAvail_r16_7_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
mobilityHistoryAvail_r16_7_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	mobilityHistoryAvail_r16_7_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
mobilityHistoryAvail_r16_7_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mobilityHistoryAvail_r16_7_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
mobilityHistoryAvail_r16_7_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	mobilityHistoryAvail_r16_7_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
mobilityHistoryAvail_r16_7_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mobilityHistoryAvail_r16_7_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
mobilityState_r16_9_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
mobilityState_r16_9_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
mobilityState_r16_9_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	mobilityState_r16_9_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
mobilityState_r16_9_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	mobilityState_r16_9_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
mobilityState_r16_9_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	mobilityState_r16_9_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
mobilityState_r16_9_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mobilityState_r16_9_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
mobilityState_r16_9_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	mobilityState_r16_9_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
mobilityState_r16_9_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mobilityState_r16_9_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const asn_INTEGER_enum_map_t asn_MAP_iab_NodeIndication_r16_value2enum_2[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_iab_NodeIndication_r16_enum2value_2[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_iab_NodeIndication_r16_specs_2 = {
	asn_MAP_iab_NodeIndication_r16_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_iab_NodeIndication_r16_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_iab_NodeIndication_r16_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_iab_NodeIndication_r16_2 = {
	"iab-NodeIndication-r16",
	"iab-NodeIndication-r16",
	iab_NodeIndication_r16_2_free,
	iab_NodeIndication_r16_2_print,
	iab_NodeIndication_r16_2_constraint,
	iab_NodeIndication_r16_2_decode_ber,
	iab_NodeIndication_r16_2_encode_der,
	iab_NodeIndication_r16_2_decode_xer,
	iab_NodeIndication_r16_2_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_iab_NodeIndication_r16_tags_2,
	sizeof(asn_DEF_iab_NodeIndication_r16_tags_2)
		/sizeof(asn_DEF_iab_NodeIndication_r16_tags_2[0]) - 1, /* 1 */
	asn_DEF_iab_NodeIndication_r16_tags_2,	/* Same as above */
	sizeof(asn_DEF_iab_NodeIndication_r16_tags_2)
		/sizeof(asn_DEF_iab_NodeIndication_r16_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_iab_NodeIndication_r16_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_idleMeasAvailable_r16_value2enum_4[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_idleMeasAvailable_r16_enum2value_4[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_idleMeasAvailable_r16_specs_4 = {
	asn_MAP_idleMeasAvailable_r16_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_idleMeasAvailable_r16_enum2value_4,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_idleMeasAvailable_r16_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_idleMeasAvailable_r16_4 = {
	"idleMeasAvailable-r16",
	"idleMeasAvailable-r16",
	idleMeasAvailable_r16_4_free,
	idleMeasAvailable_r16_4_print,
	idleMeasAvailable_r16_4_constraint,
	idleMeasAvailable_r16_4_decode_ber,
	idleMeasAvailable_r16_4_encode_der,
	idleMeasAvailable_r16_4_decode_xer,
	idleMeasAvailable_r16_4_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_idleMeasAvailable_r16_tags_4,
	sizeof(asn_DEF_idleMeasAvailable_r16_tags_4)
		/sizeof(asn_DEF_idleMeasAvailable_r16_tags_4[0]) - 1, /* 1 */
	asn_DEF_idleMeasAvailable_r16_tags_4,	/* Same as above */
	sizeof(asn_DEF_idleMeasAvailable_r16_tags_4)
		/sizeof(asn_DEF_idleMeasAvailable_r16_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_idleMeasAvailable_r16_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_mobilityHistoryAvail_r16_value2enum_7[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_mobilityHistoryAvail_r16_enum2value_7[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_mobilityHistoryAvail_r16_specs_7 = {
	asn_MAP_mobilityHistoryAvail_r16_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_mobilityHistoryAvail_r16_enum2value_7,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_mobilityHistoryAvail_r16_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mobilityHistoryAvail_r16_7 = {
	"mobilityHistoryAvail-r16",
	"mobilityHistoryAvail-r16",
	mobilityHistoryAvail_r16_7_free,
	mobilityHistoryAvail_r16_7_print,
	mobilityHistoryAvail_r16_7_constraint,
	mobilityHistoryAvail_r16_7_decode_ber,
	mobilityHistoryAvail_r16_7_encode_der,
	mobilityHistoryAvail_r16_7_decode_xer,
	mobilityHistoryAvail_r16_7_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mobilityHistoryAvail_r16_tags_7,
	sizeof(asn_DEF_mobilityHistoryAvail_r16_tags_7)
		/sizeof(asn_DEF_mobilityHistoryAvail_r16_tags_7[0]) - 1, /* 1 */
	asn_DEF_mobilityHistoryAvail_r16_tags_7,	/* Same as above */
	sizeof(asn_DEF_mobilityHistoryAvail_r16_tags_7)
		/sizeof(asn_DEF_mobilityHistoryAvail_r16_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mobilityHistoryAvail_r16_specs_7	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_mobilityState_r16_value2enum_9[] = {
	{ 0,	6,	"normal" },
	{ 1,	6,	"medium" },
	{ 2,	4,	"high" },
	{ 3,	5,	"spare" }
};
static const unsigned int asn_MAP_mobilityState_r16_enum2value_9[] = {
	2,	/* high(2) */
	1,	/* medium(1) */
	0,	/* normal(0) */
	3	/* spare(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_mobilityState_r16_specs_9 = {
	asn_MAP_mobilityState_r16_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_mobilityState_r16_enum2value_9,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_mobilityState_r16_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mobilityState_r16_9 = {
	"mobilityState-r16",
	"mobilityState-r16",
	mobilityState_r16_9_free,
	mobilityState_r16_9_print,
	mobilityState_r16_9_constraint,
	mobilityState_r16_9_decode_ber,
	mobilityState_r16_9_encode_der,
	mobilityState_r16_9_decode_xer,
	mobilityState_r16_9_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mobilityState_r16_tags_9,
	sizeof(asn_DEF_mobilityState_r16_tags_9)
		/sizeof(asn_DEF_mobilityState_r16_tags_9[0]) - 1, /* 1 */
	asn_DEF_mobilityState_r16_tags_9,	/* Same as above */
	sizeof(asn_DEF_mobilityState_r16_tags_9)
		/sizeof(asn_DEF_mobilityState_r16_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mobilityState_r16_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RRCSetupComplete_v1610_IEs_1[] = {
	{ ATF_POINTER, 6, offsetof(struct RRCSetupComplete_v1610_IEs, iab_NodeIndication_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_iab_NodeIndication_r16_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iab-NodeIndication-r16"
		},
	{ ATF_POINTER, 5, offsetof(struct RRCSetupComplete_v1610_IEs, idleMeasAvailable_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_idleMeasAvailable_r16_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idleMeasAvailable-r16"
		},
	{ ATF_POINTER, 4, offsetof(struct RRCSetupComplete_v1610_IEs, ue_MeasurementsAvailable_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_MeasurementsAvailable_r16,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ue-MeasurementsAvailable-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct RRCSetupComplete_v1610_IEs, mobilityHistoryAvail_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mobilityHistoryAvail_r16_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mobilityHistoryAvail-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct RRCSetupComplete_v1610_IEs, mobilityState_r16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mobilityState_r16_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mobilityState-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCSetupComplete_v1610_IEs, nonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCSetupComplete_v1690_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nonCriticalExtension"
		},
};
static const ber_tlv_tag_t asn_DEF_RRCSetupComplete_v1610_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRCSetupComplete_v1610_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* iab-NodeIndication-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* idleMeasAvailable-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ue-MeasurementsAvailable-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mobilityHistoryAvail-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* mobilityState-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* nonCriticalExtension */
};
static asn_SEQUENCE_specifics_t asn_SPC_RRCSetupComplete_v1610_IEs_specs_1 = {
	sizeof(struct RRCSetupComplete_v1610_IEs),
	offsetof(struct RRCSetupComplete_v1610_IEs, _asn_ctx),
	asn_MAP_RRCSetupComplete_v1610_IEs_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RRCSetupComplete_v1610_IEs = {
	"RRCSetupComplete-v1610-IEs",
	"RRCSetupComplete-v1610-IEs",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RRCSetupComplete_v1610_IEs_tags_1,
	sizeof(asn_DEF_RRCSetupComplete_v1610_IEs_tags_1)
		/sizeof(asn_DEF_RRCSetupComplete_v1610_IEs_tags_1[0]), /* 1 */
	asn_DEF_RRCSetupComplete_v1610_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCSetupComplete_v1610_IEs_tags_1)
		/sizeof(asn_DEF_RRCSetupComplete_v1610_IEs_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RRCSetupComplete_v1610_IEs_1,
	6,	/* Elements count */
	&asn_SPC_RRCSetupComplete_v1610_IEs_specs_1	/* Additional specs */
};

