/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#include "RRCSetupComplete-v1800-IEs.h"

static int
ncr_NodeIndication_r18_2_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
ncr_NodeIndication_r18_2_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
ncr_NodeIndication_r18_2_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	ncr_NodeIndication_r18_2_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
ncr_NodeIndication_r18_2_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	ncr_NodeIndication_r18_2_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
ncr_NodeIndication_r18_2_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	ncr_NodeIndication_r18_2_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
ncr_NodeIndication_r18_2_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ncr_NodeIndication_r18_2_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
ncr_NodeIndication_r18_2_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	ncr_NodeIndication_r18_2_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
ncr_NodeIndication_r18_2_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ncr_NodeIndication_r18_2_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
musim_CapRestrictionInd_r18_4_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
musim_CapRestrictionInd_r18_4_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
musim_CapRestrictionInd_r18_4_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	musim_CapRestrictionInd_r18_4_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
musim_CapRestrictionInd_r18_4_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	musim_CapRestrictionInd_r18_4_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
musim_CapRestrictionInd_r18_4_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	musim_CapRestrictionInd_r18_4_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
musim_CapRestrictionInd_r18_4_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	musim_CapRestrictionInd_r18_4_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
musim_CapRestrictionInd_r18_4_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	musim_CapRestrictionInd_r18_4_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
musim_CapRestrictionInd_r18_4_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	musim_CapRestrictionInd_r18_4_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
flightPathInfoAvailable_r18_6_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
flightPathInfoAvailable_r18_6_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
flightPathInfoAvailable_r18_6_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	flightPathInfoAvailable_r18_6_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
flightPathInfoAvailable_r18_6_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	flightPathInfoAvailable_r18_6_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
flightPathInfoAvailable_r18_6_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	flightPathInfoAvailable_r18_6_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
flightPathInfoAvailable_r18_6_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	flightPathInfoAvailable_r18_6_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
flightPathInfoAvailable_r18_6_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	flightPathInfoAvailable_r18_6_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
flightPathInfoAvailable_r18_6_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	flightPathInfoAvailable_r18_6_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
measConfigReportAppLayerAvailable_r18_8_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
measConfigReportAppLayerAvailable_r18_8_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
measConfigReportAppLayerAvailable_r18_8_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	measConfigReportAppLayerAvailable_r18_8_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
measConfigReportAppLayerAvailable_r18_8_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	measConfigReportAppLayerAvailable_r18_8_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
measConfigReportAppLayerAvailable_r18_8_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	measConfigReportAppLayerAvailable_r18_8_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
measConfigReportAppLayerAvailable_r18_8_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	measConfigReportAppLayerAvailable_r18_8_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
measConfigReportAppLayerAvailable_r18_8_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	measConfigReportAppLayerAvailable_r18_8_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
measConfigReportAppLayerAvailable_r18_8_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	measConfigReportAppLayerAvailable_r18_8_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
mobileIAB_NodeIndication_r18_10_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
mobileIAB_NodeIndication_r18_10_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
mobileIAB_NodeIndication_r18_10_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	mobileIAB_NodeIndication_r18_10_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
mobileIAB_NodeIndication_r18_10_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	mobileIAB_NodeIndication_r18_10_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
mobileIAB_NodeIndication_r18_10_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	mobileIAB_NodeIndication_r18_10_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
mobileIAB_NodeIndication_r18_10_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mobileIAB_NodeIndication_r18_10_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
mobileIAB_NodeIndication_r18_10_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	mobileIAB_NodeIndication_r18_10_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
mobileIAB_NodeIndication_r18_10_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mobileIAB_NodeIndication_r18_10_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
reselectionMeasAvailable_r18_12_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
reselectionMeasAvailable_r18_12_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
reselectionMeasAvailable_r18_12_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	reselectionMeasAvailable_r18_12_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
reselectionMeasAvailable_r18_12_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	reselectionMeasAvailable_r18_12_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
reselectionMeasAvailable_r18_12_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	reselectionMeasAvailable_r18_12_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
reselectionMeasAvailable_r18_12_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reselectionMeasAvailable_r18_12_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
reselectionMeasAvailable_r18_12_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	reselectionMeasAvailable_r18_12_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
reselectionMeasAvailable_r18_12_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reselectionMeasAvailable_r18_12_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const asn_INTEGER_enum_map_t asn_MAP_ncr_NodeIndication_r18_value2enum_2[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_ncr_NodeIndication_r18_enum2value_2[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ncr_NodeIndication_r18_specs_2 = {
	asn_MAP_ncr_NodeIndication_r18_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_ncr_NodeIndication_r18_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ncr_NodeIndication_r18_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ncr_NodeIndication_r18_2 = {
	"ncr-NodeIndication-r18",
	"ncr-NodeIndication-r18",
	ncr_NodeIndication_r18_2_free,
	ncr_NodeIndication_r18_2_print,
	ncr_NodeIndication_r18_2_constraint,
	ncr_NodeIndication_r18_2_decode_ber,
	ncr_NodeIndication_r18_2_encode_der,
	ncr_NodeIndication_r18_2_decode_xer,
	ncr_NodeIndication_r18_2_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ncr_NodeIndication_r18_tags_2,
	sizeof(asn_DEF_ncr_NodeIndication_r18_tags_2)
		/sizeof(asn_DEF_ncr_NodeIndication_r18_tags_2[0]) - 1, /* 1 */
	asn_DEF_ncr_NodeIndication_r18_tags_2,	/* Same as above */
	sizeof(asn_DEF_ncr_NodeIndication_r18_tags_2)
		/sizeof(asn_DEF_ncr_NodeIndication_r18_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ncr_NodeIndication_r18_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_musim_CapRestrictionInd_r18_value2enum_4[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_musim_CapRestrictionInd_r18_enum2value_4[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_musim_CapRestrictionInd_r18_specs_4 = {
	asn_MAP_musim_CapRestrictionInd_r18_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_musim_CapRestrictionInd_r18_enum2value_4,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_musim_CapRestrictionInd_r18_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_musim_CapRestrictionInd_r18_4 = {
	"musim-CapRestrictionInd-r18",
	"musim-CapRestrictionInd-r18",
	musim_CapRestrictionInd_r18_4_free,
	musim_CapRestrictionInd_r18_4_print,
	musim_CapRestrictionInd_r18_4_constraint,
	musim_CapRestrictionInd_r18_4_decode_ber,
	musim_CapRestrictionInd_r18_4_encode_der,
	musim_CapRestrictionInd_r18_4_decode_xer,
	musim_CapRestrictionInd_r18_4_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_musim_CapRestrictionInd_r18_tags_4,
	sizeof(asn_DEF_musim_CapRestrictionInd_r18_tags_4)
		/sizeof(asn_DEF_musim_CapRestrictionInd_r18_tags_4[0]) - 1, /* 1 */
	asn_DEF_musim_CapRestrictionInd_r18_tags_4,	/* Same as above */
	sizeof(asn_DEF_musim_CapRestrictionInd_r18_tags_4)
		/sizeof(asn_DEF_musim_CapRestrictionInd_r18_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_musim_CapRestrictionInd_r18_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_flightPathInfoAvailable_r18_value2enum_6[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_flightPathInfoAvailable_r18_enum2value_6[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_flightPathInfoAvailable_r18_specs_6 = {
	asn_MAP_flightPathInfoAvailable_r18_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_flightPathInfoAvailable_r18_enum2value_6,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_flightPathInfoAvailable_r18_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_flightPathInfoAvailable_r18_6 = {
	"flightPathInfoAvailable-r18",
	"flightPathInfoAvailable-r18",
	flightPathInfoAvailable_r18_6_free,
	flightPathInfoAvailable_r18_6_print,
	flightPathInfoAvailable_r18_6_constraint,
	flightPathInfoAvailable_r18_6_decode_ber,
	flightPathInfoAvailable_r18_6_encode_der,
	flightPathInfoAvailable_r18_6_decode_xer,
	flightPathInfoAvailable_r18_6_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_flightPathInfoAvailable_r18_tags_6,
	sizeof(asn_DEF_flightPathInfoAvailable_r18_tags_6)
		/sizeof(asn_DEF_flightPathInfoAvailable_r18_tags_6[0]) - 1, /* 1 */
	asn_DEF_flightPathInfoAvailable_r18_tags_6,	/* Same as above */
	sizeof(asn_DEF_flightPathInfoAvailable_r18_tags_6)
		/sizeof(asn_DEF_flightPathInfoAvailable_r18_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_flightPathInfoAvailable_r18_specs_6	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_measConfigReportAppLayerAvailable_r18_value2enum_8[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_measConfigReportAppLayerAvailable_r18_enum2value_8[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_measConfigReportAppLayerAvailable_r18_specs_8 = {
	asn_MAP_measConfigReportAppLayerAvailable_r18_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_measConfigReportAppLayerAvailable_r18_enum2value_8,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_measConfigReportAppLayerAvailable_r18_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measConfigReportAppLayerAvailable_r18_8 = {
	"measConfigReportAppLayerAvailable-r18",
	"measConfigReportAppLayerAvailable-r18",
	measConfigReportAppLayerAvailable_r18_8_free,
	measConfigReportAppLayerAvailable_r18_8_print,
	measConfigReportAppLayerAvailable_r18_8_constraint,
	measConfigReportAppLayerAvailable_r18_8_decode_ber,
	measConfigReportAppLayerAvailable_r18_8_encode_der,
	measConfigReportAppLayerAvailable_r18_8_decode_xer,
	measConfigReportAppLayerAvailable_r18_8_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_measConfigReportAppLayerAvailable_r18_tags_8,
	sizeof(asn_DEF_measConfigReportAppLayerAvailable_r18_tags_8)
		/sizeof(asn_DEF_measConfigReportAppLayerAvailable_r18_tags_8[0]) - 1, /* 1 */
	asn_DEF_measConfigReportAppLayerAvailable_r18_tags_8,	/* Same as above */
	sizeof(asn_DEF_measConfigReportAppLayerAvailable_r18_tags_8)
		/sizeof(asn_DEF_measConfigReportAppLayerAvailable_r18_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_measConfigReportAppLayerAvailable_r18_specs_8	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_mobileIAB_NodeIndication_r18_value2enum_10[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_mobileIAB_NodeIndication_r18_enum2value_10[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_mobileIAB_NodeIndication_r18_specs_10 = {
	asn_MAP_mobileIAB_NodeIndication_r18_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_mobileIAB_NodeIndication_r18_enum2value_10,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_mobileIAB_NodeIndication_r18_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mobileIAB_NodeIndication_r18_10 = {
	"mobileIAB-NodeIndication-r18",
	"mobileIAB-NodeIndication-r18",
	mobileIAB_NodeIndication_r18_10_free,
	mobileIAB_NodeIndication_r18_10_print,
	mobileIAB_NodeIndication_r18_10_constraint,
	mobileIAB_NodeIndication_r18_10_decode_ber,
	mobileIAB_NodeIndication_r18_10_encode_der,
	mobileIAB_NodeIndication_r18_10_decode_xer,
	mobileIAB_NodeIndication_r18_10_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mobileIAB_NodeIndication_r18_tags_10,
	sizeof(asn_DEF_mobileIAB_NodeIndication_r18_tags_10)
		/sizeof(asn_DEF_mobileIAB_NodeIndication_r18_tags_10[0]) - 1, /* 1 */
	asn_DEF_mobileIAB_NodeIndication_r18_tags_10,	/* Same as above */
	sizeof(asn_DEF_mobileIAB_NodeIndication_r18_tags_10)
		/sizeof(asn_DEF_mobileIAB_NodeIndication_r18_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mobileIAB_NodeIndication_r18_specs_10	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_reselectionMeasAvailable_r18_value2enum_12[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_reselectionMeasAvailable_r18_enum2value_12[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_reselectionMeasAvailable_r18_specs_12 = {
	asn_MAP_reselectionMeasAvailable_r18_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_reselectionMeasAvailable_r18_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_reselectionMeasAvailable_r18_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reselectionMeasAvailable_r18_12 = {
	"reselectionMeasAvailable-r18",
	"reselectionMeasAvailable-r18",
	reselectionMeasAvailable_r18_12_free,
	reselectionMeasAvailable_r18_12_print,
	reselectionMeasAvailable_r18_12_constraint,
	reselectionMeasAvailable_r18_12_decode_ber,
	reselectionMeasAvailable_r18_12_encode_der,
	reselectionMeasAvailable_r18_12_decode_xer,
	reselectionMeasAvailable_r18_12_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_reselectionMeasAvailable_r18_tags_12,
	sizeof(asn_DEF_reselectionMeasAvailable_r18_tags_12)
		/sizeof(asn_DEF_reselectionMeasAvailable_r18_tags_12[0]) - 1, /* 1 */
	asn_DEF_reselectionMeasAvailable_r18_tags_12,	/* Same as above */
	sizeof(asn_DEF_reselectionMeasAvailable_r18_tags_12)
		/sizeof(asn_DEF_reselectionMeasAvailable_r18_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_reselectionMeasAvailable_r18_specs_12	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtension_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_14 = {
	sizeof(struct RRCSetupComplete_v1800_IEs__nonCriticalExtension),
	offsetof(struct RRCSetupComplete_v1800_IEs__nonCriticalExtension, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_14 = {
	"nonCriticalExtension",
	"nonCriticalExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtension_tags_14,
	sizeof(asn_DEF_nonCriticalExtension_tags_14)
		/sizeof(asn_DEF_nonCriticalExtension_tags_14[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtension_tags_14,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtension_tags_14)
		/sizeof(asn_DEF_nonCriticalExtension_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RRCSetupComplete_v1800_IEs_1[] = {
	{ ATF_POINTER, 7, offsetof(struct RRCSetupComplete_v1800_IEs, ncr_NodeIndication_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ncr_NodeIndication_r18_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ncr-NodeIndication-r18"
		},
	{ ATF_POINTER, 6, offsetof(struct RRCSetupComplete_v1800_IEs, musim_CapRestrictionInd_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_musim_CapRestrictionInd_r18_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"musim-CapRestrictionInd-r18"
		},
	{ ATF_POINTER, 5, offsetof(struct RRCSetupComplete_v1800_IEs, flightPathInfoAvailable_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_flightPathInfoAvailable_r18_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"flightPathInfoAvailable-r18"
		},
	{ ATF_POINTER, 4, offsetof(struct RRCSetupComplete_v1800_IEs, measConfigReportAppLayerAvailable_r18),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_measConfigReportAppLayerAvailable_r18_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"measConfigReportAppLayerAvailable-r18"
		},
	{ ATF_POINTER, 3, offsetof(struct RRCSetupComplete_v1800_IEs, mobileIAB_NodeIndication_r18),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mobileIAB_NodeIndication_r18_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mobileIAB-NodeIndication-r18"
		},
	{ ATF_POINTER, 2, offsetof(struct RRCSetupComplete_v1800_IEs, reselectionMeasAvailable_r18),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_reselectionMeasAvailable_r18_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reselectionMeasAvailable-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCSetupComplete_v1800_IEs, nonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_nonCriticalExtension_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nonCriticalExtension"
		},
};
static const ber_tlv_tag_t asn_DEF_RRCSetupComplete_v1800_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRCSetupComplete_v1800_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ncr-NodeIndication-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* musim-CapRestrictionInd-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* flightPathInfoAvailable-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* measConfigReportAppLayerAvailable-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* mobileIAB-NodeIndication-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* reselectionMeasAvailable-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* nonCriticalExtension */
};
static asn_SEQUENCE_specifics_t asn_SPC_RRCSetupComplete_v1800_IEs_specs_1 = {
	sizeof(struct RRCSetupComplete_v1800_IEs),
	offsetof(struct RRCSetupComplete_v1800_IEs, _asn_ctx),
	asn_MAP_RRCSetupComplete_v1800_IEs_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RRCSetupComplete_v1800_IEs = {
	"RRCSetupComplete-v1800-IEs",
	"RRCSetupComplete-v1800-IEs",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RRCSetupComplete_v1800_IEs_tags_1,
	sizeof(asn_DEF_RRCSetupComplete_v1800_IEs_tags_1)
		/sizeof(asn_DEF_RRCSetupComplete_v1800_IEs_tags_1[0]), /* 1 */
	asn_DEF_RRCSetupComplete_v1800_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCSetupComplete_v1800_IEs_tags_1)
		/sizeof(asn_DEF_RRCSetupComplete_v1800_IEs_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RRCSetupComplete_v1800_IEs_1,
	7,	/* Elements count */
	&asn_SPC_RRCSetupComplete_v1800_IEs_specs_1	/* Additional specs */
};

