/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "RRC.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -pdu=all`
 */

#ifndef	_SL_L2RemoteUE_Config_r17_H_
#define	_SL_L2RemoteUE_Config_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SL-L2RemoteUE-Config-r17 */
typedef struct SL_L2RemoteUE_Config_r17 {
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_L2RemoteUE_Config_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_L2RemoteUE_Config_r17;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_L2RemoteUE_Config_r17_H_ */
#include <asn_internal.h>
